name: "✨ Improve an Existing Feature"
description: "Suggest an improvement for a feature that is already implemented."
title: "[IMPROVE] "
labels: ["enhancement"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        > [!NOTE]
        > Thanks for taking the time to write to improve an existing feature! Please be as detailed as possible.
        
  - type: textarea
    id: tedious-feature
    attributes:
      label: "Is there any feature or implemented method that is tedious to use?"
      description: "Please describe which feature is complicated or tedious and explain why."
      placeholder: "e.g., 'The process for exporting images requires too many clicks...'"
    validations:
      required: true
      
  - type: textarea
    id: proposed-improvement
    attributes:
      label: "How would you improve what was mentioned before?"
      description: "Provide a clear and concise description of your proposed solution."
      placeholder: "e.g., 'It could be simplified by adding a right-click context menu option to export directly.'"
    validations:
      required: true
