using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Numerics;
using AssetsManager.Views.Models.Viewer;
using LeagueToolkit.Core.Meta;
using LeagueToolkit.Core.Meta.Properties;


namespace AssetsManager.Services.Viewer.Vfx.Parsing
{
    internal static class VfxParsingSchema
    {
        // class hashes
        internal static readonly uint SystemClass  = VfxParsingHash.Fnv1a("VfxSystemDefinitionData");
        internal static readonly uint EmitterClass = VfxParsingHash.Fnv1a("VfxEmitterDefinitionData");
        internal static readonly uint SkinCharacterDataPropertiesClass = VfxParsingHash.Fnv1a("SkinCharacterDataProperties");

        // system fields
        internal static readonly uint F_particleName = VfxParsingHash.Fnv1a("particleName");
        internal static readonly uint F_particlePath = VfxParsingHash.Fnv1a("particlePath");
        internal static readonly uint F_visibilityRadius = VfxParsingHash.Fnv1a("visibilityRadius");
        internal static readonly uint F_transform = VfxParsingHash.Fnv1a("transform");
        internal static readonly uint F_systemFlags = VfxParsingHash.Fnv1a("flags");
        internal static readonly uint F_buildUpTime = VfxParsingHash.Fnv1a("buildUpTime");
        internal const int DefaultSystemFlags = 0xd4;
        internal const int AnalyticDragMotionFlag = 0x100;
        internal static readonly uint[] EmitterLists =
        {
            VfxParsingHash.Fnv1a("complexEmitterDefinitionData"),
            VfxParsingHash.Fnv1a("simpleEmitterDefinitionData")
        };
        internal static readonly uint F_materialOverrideDefinitions = VfxParsingHash.Fnv1a("materialOverrideDefinitions");
        internal static readonly uint F_assetRemappingTable = VfxParsingHash.Fnv1a("assetRemappingTable");

        // emitter fields
        internal static readonly uint F_emitterName   = VfxParsingHash.Fnv1a("emitterName");
        internal static readonly uint F_rate          = VfxParsingHash.Fnv1a("rate");
        internal static readonly uint F_particleLife  = VfxParsingHash.Fnv1a("particleLifetime");
        internal static readonly uint F_lifetime      = VfxParsingHash.Fnv1a("lifetime");
        internal static readonly uint F_particleLinger= VfxParsingHash.Fnv1a("particleLinger");
        internal static readonly uint F_particleLingerType = VfxParsingHash.Fnv1a("particleLingerType");
        internal static readonly uint F_emitterLinger = VfxParsingHash.Fnv1a("emitterLinger");
        internal static readonly uint F_linger = VfxParsingHash.Fnv1a("Linger");
        internal static readonly uint F_useLingerRotation = VfxParsingHash.Fnv1a("UseLingerRotation");
        internal static readonly uint F_lingerRotation = VfxParsingHash.Fnv1a("LingerRotation");
        internal static readonly uint F_useLingerScale = VfxParsingHash.Fnv1a("UseLingerScale");
        internal static readonly uint F_lingerScale = VfxParsingHash.Fnv1a("LingerScale");
        internal static readonly uint F_useLingerColor = VfxParsingHash.Fnv1a("UseSeparateLingerColor");
        internal static readonly uint F_lingerColor = VfxParsingHash.Fnv1a("SeparateLingerColor");
        internal static readonly uint F_useLingerAcceleration = VfxParsingHash.Fnv1a("UseKeyedLingerAcceleration");
        internal static readonly uint F_lingerAcceleration = VfxParsingHash.Fnv1a("KeyedLingerAcceleration");
        internal static readonly uint F_useLingerVelocity = VfxParsingHash.Fnv1a("UseKeyedLingerVelocity");
        internal static readonly uint F_lingerVelocity = VfxParsingHash.Fnv1a("KeyedLingerVelocity");
        internal static readonly uint F_useLingerDrag = VfxParsingHash.Fnv1a("UseKeyedLingerDrag");
        internal static readonly uint F_lingerDrag = VfxParsingHash.Fnv1a("KeyedLingerDrag");
        internal static readonly uint F_timeBefore    = VfxParsingHash.Fnv1a("timeBeforeFirstEmission");
        internal static readonly uint F_isSingle      = VfxParsingHash.Fnv1a("isSingleParticle");
        internal static readonly uint F_disabled      = VfxParsingHash.Fnv1a("disabled");
        internal static readonly uint F_importance    = VfxParsingHash.Fnv1a("importance");
        internal static readonly uint F_colorblindVisibility = VfxParsingHash.Fnv1a("colorblindVisibility");
        internal static readonly uint F_miscRenderFlags = VfxParsingHash.Fnv1a("miscRenderFlags");
        internal static readonly uint F_meshRenderFlags = VfxParsingHash.Fnv1a("meshRenderFlags");
        internal static readonly uint F_useNavmeshMask = VfxParsingHash.Fnv1a("useNavmeshMask");
        internal static readonly uint F_depthBiasFactors = VfxParsingHash.Fnv1a("depthBiasFactors");
        internal static readonly uint F_depthPushPull = VfxParsingHash.Fnv1a("DepthPushPull");
        internal static readonly uint F_isRotationEnabled = VfxParsingHash.Fnv1a("isRotationEnabled");
        internal static readonly uint F_rateIsPeriod  = VfxParsingHash.Fnv1a("rateIsPeriod");
        internal static readonly uint F_birthTimePeriod = VfxParsingHash.Fnv1a("birthTimePeriod");
        internal static readonly uint F_isLoop        = VfxParsingHash.Fnv1a("isLoop");
        internal static readonly uint F_blendMode     = VfxParsingHash.Fnv1a("blendMode");
        internal static readonly uint F_renderPass    = VfxParsingHash.Fnv1a("pass");
        internal static readonly uint F_alphaRef      = VfxParsingHash.Fnv1a("alphaRef");
        internal static readonly uint F_texAddress    = VfxParsingHash.Fnv1a("texAddressModeBase");
        internal static readonly uint F_uvScrollClamp = VfxParsingHash.Fnv1a("uvScrollClamp");
        internal static readonly uint F_textureFlipU  = VfxParsingHash.Fnv1a("TextureFlipU");
        internal static readonly uint F_textureFlipV  = VfxParsingHash.Fnv1a("TextureFlipV");
        internal static readonly uint F_disableCull   = VfxParsingHash.Fnv1a("disableBackfaceCull");
        internal static readonly uint F_birthScale0   = VfxParsingHash.Fnv1a("birthScale0");
        internal static readonly uint F_birthScale1   = VfxParsingHash.Fnv1a("birthScale1");
        internal static readonly uint F_scale0        = VfxParsingHash.Fnv1a("scale0");
        internal static readonly uint F_birthColor    = VfxParsingHash.Fnv1a("birthColor");
        internal static readonly uint F_color         = VfxParsingHash.Fnv1a("color");
        internal static readonly uint F_modulationFactor = VfxParsingHash.Fnv1a("modulationFactor");
        internal static readonly uint F_particleColorTex = VfxParsingHash.Fnv1a("particleColorTexture");
        internal static readonly uint F_colorLookUpX  = VfxParsingHash.Fnv1a("colorLookUpTypeX");
        internal static readonly uint F_colorLookUpY  = VfxParsingHash.Fnv1a("colorLookUpTypeY");
        internal static readonly uint F_colorLookUpOffsets = VfxParsingHash.Fnv1a("colorLookUpOffsets");
        internal static readonly uint F_colorLookUpScales = VfxParsingHash.Fnv1a("colorLookUpScales");
        internal static readonly uint F_colorRenderFlags = VfxParsingHash.Fnv1a("colorRenderFlags");
        internal static readonly uint F_isTexturePixelated = VfxParsingHash.Fnv1a("isTexturePixelated");
        internal static readonly uint F_birthVelocity = VfxParsingHash.Fnv1a("birthVelocity");
        internal static readonly uint F_velocity      = VfxParsingHash.Fnv1a("velocity");
        internal static readonly uint F_birthAccel    = VfxParsingHash.Fnv1a("birthAcceleration");
        internal static readonly uint F_accel         = VfxParsingHash.Fnv1a("acceleration");
        internal static readonly uint F_birthOrbital  = VfxParsingHash.Fnv1a("birthOrbitalVelocity");
        internal static readonly uint F_worldAccel    = VfxParsingHash.Fnv1a("worldAcceleration");
        internal static readonly uint F_birthDrag     = VfxParsingHash.Fnv1a("birthDrag");
        internal static readonly uint F_drag          = VfxParsingHash.Fnv1a("drag");
        internal static readonly uint F_birthRotation = VfxParsingHash.Fnv1a("birthRotation0");
        internal static readonly uint F_rotation      = VfxParsingHash.Fnv1a("rotation0");
        internal static readonly uint F_rotation1     = VfxParsingHash.Fnv1a("rotation1");
        internal static readonly uint F_birthRotVel0  = VfxParsingHash.Fnv1a("birthRotationalVelocity0");
        internal static readonly uint F_birthRotAccel = VfxParsingHash.Fnv1a("birthRotationalAcceleration");
        internal static readonly uint F_emitterPos    = VfxParsingHash.Fnv1a("emitterPosition");
        internal static readonly uint F_isEmitterSpace = VfxParsingHash.Fnv1a("IsEmitterSpace");
        internal static readonly uint F_isLocalOrientation = VfxParsingHash.Fnv1a("isLocalOrientation");
        internal static readonly uint F_particleIsLocalOrientation = VfxParsingHash.Fnv1a("particleIsLocalOrientation");
        internal static readonly uint F_isFollowingTerrain = VfxParsingHash.Fnv1a("isFollowingTerrain");
        internal static readonly uint F_isGroundLayer = VfxParsingHash.Fnv1a("isGroundLayer");
        internal static readonly uint F_isUniformScale = VfxParsingHash.Fnv1a("isUniformScale");
        internal static readonly uint F_uvMode        = VfxParsingHash.Fnv1a("uvMode");
        internal static readonly uint F_bindWeight    = VfxParsingHash.Fnv1a("bindWeight");
        internal static readonly uint F_flexShapeDefinition = VfxParsingHash.Fnv1a("FlexShapeDefinition");
        internal static readonly uint F_scaleBirthScaleByBoundObjectSize =
            VfxParsingHash.Fnv1a("scaleBirthScaleByBoundObjectSize");
        internal static readonly uint F_scaleEmitOffsetByBoundObjectSize =
            VfxParsingHash.Fnv1a("scaleEmitOffsetByBoundObjectSize");
        internal static readonly uint F_directionVelocityScale = VfxParsingHash.Fnv1a("directionVelocityScale");
        internal static readonly uint F_directionVelocityMinScale = VfxParsingHash.Fnv1a("directionVelocityMinScale");
        internal static readonly uint F_paletteDefinition = VfxParsingHash.Fnv1a("paletteDefinition");
        internal static readonly uint F_paletteCount = VfxParsingHash.Fnv1a("paletteCount");
        internal static readonly uint F_paletteSelector = VfxParsingHash.Fnv1a("paletteSelector");
        internal static readonly uint F_paletteTexture = VfxParsingHash.Fnv1a("paletteTexture");
        internal static readonly uint F_paletteSourceMixColor = VfxParsingHash.Fnv1a("paletteSrcMixColor");
        internal static readonly uint F_palleteSourceMixColor = VfxParsingHash.Fnv1a("palleteSrcMixColor");
        internal static readonly uint F_paletteScrollU = VfxParsingHash.Fnv1a("PaletteUAnimationCurve");
        internal static readonly uint F_paletteScrollV = VfxParsingHash.Fnv1a("PaletteVAnimationCurve");
        internal static readonly uint F_paletteAddressMode = VfxParsingHash.Fnv1a("PaletteTextureAddressMode");
        internal static readonly uint F_audio = VfxParsingHash.Fnv1a("Audio");
        internal static readonly uint F_soundOnCreate = VfxParsingHash.Fnv1a("SoundOnCreate");
        internal static readonly uint F_particlesShareRandomValue = VfxParsingHash.Fnv1a("ParticlesShareRandomValue");
        internal static readonly uint F_filtering = VfxParsingHash.Fnv1a("Filtering");
        internal static readonly uint F_keywordsExcluded = VfxParsingHash.Fnv1a("keywordsExcluded");
        internal static readonly uint F_customMaterial = VfxParsingHash.Fnv1a("CustomMaterial");
        internal static readonly uint F_stencilMode = VfxParsingHash.Fnv1a("stencilMode");
        internal static readonly uint F_stencilRef = VfxParsingHash.Fnv1a("stencilRef");
        internal static readonly uint F_stencilReferenceId = VfxParsingHash.Fnv1a("StencilReferenceId");
        internal static readonly uint F_writeAlphaOnly = VfxParsingHash.Fnv1a("WriteAlphaOnly");
        internal static readonly uint F_renderPhaseOverride = VfxParsingHash.Fnv1a("renderPhaseOverride");
        internal static readonly uint F_sortEmittersByPos = VfxParsingHash.Fnv1a("SortEmittersByPos");
        internal static readonly uint F_emissionMeshName = VfxParsingHash.Fnv1a("emissionMeshName");
        internal static readonly uint F_emissionSurfaceDefinition = VfxParsingHash.Fnv1a("emissionSurfaceDefinition");
        internal static readonly uint F_emissionSurface = VfxParsingHash.Fnv1a("EmissionSurface");
        internal static readonly uint F_emissionMesh = VfxParsingHash.Fnv1a("meshName");
        internal static readonly uint F_emissionSkeleton = VfxParsingHash.Fnv1a("skeletonName");
        internal static readonly uint F_emissionAnimation = VfxParsingHash.Fnv1a("AnimationName");
        internal static readonly uint F_emissionSubmeshes = VfxParsingHash.Fnv1a("Submeshes");
        internal static readonly uint F_emissionJointMask = VfxParsingHash.Fnv1a("JointMask");
        internal static readonly uint F_emissionMeshScale = VfxParsingHash.Fnv1a("meshScale");
        internal static readonly uint F_emissionMaxJointWeights = VfxParsingHash.Fnv1a("maxJointWeights");
        internal static readonly uint F_emissionUseSurfaceNormal = VfxParsingHash.Fnv1a("useSurfaceNormalForBirthPhysics");
        internal static readonly uint F_useEmissionMeshNormal = VfxParsingHash.Fnv1a("useEmissionMeshNormalForBirth");
        internal static readonly uint F_customMaterialLink = VfxParsingHash.Fnv1a("Material");
        internal static readonly uint EmissionSkeletonClass = VfxParsingHash.Fnv1a("VfxEmissionSkeletonData");
        internal static readonly uint EmissionMeshClass = VfxParsingHash.Fnv1a("VfxEmissionMeshData");
        internal static readonly uint F_translationOverride = VfxParsingHash.Fnv1a("translationOverride");
        internal static readonly uint F_rotationOverride = VfxParsingHash.Fnv1a("rotationOverride");
        internal static readonly uint F_scaleOverride = VfxParsingHash.Fnv1a("scaleOverride");
        internal static readonly uint F_period = VfxParsingHash.Fnv1a("period");
        internal static readonly uint F_timeActiveDuringPeriod = VfxParsingHash.Fnv1a("timeActiveDuringPeriod");
        internal const uint F_spawnShape              = 0x3bf0b4ed; // SpawnShape
        internal static readonly uint F_emitOffset    = VfxParsingHash.Fnv1a("emitOffset");
        internal static readonly uint F_birthTranslation = VfxParsingHash.Fnv1a("birthTranslation");
        internal static readonly uint F_emitRotAxes   = VfxParsingHash.Fnv1a("emitRotationAxes");
        internal static readonly uint F_emitRotAngles = VfxParsingHash.Fnv1a("emitRotationAngles");
        internal static readonly uint F_shapeSize      = VfxParsingHash.Fnv1a("Size");
        internal static readonly uint F_shapeRadius    = VfxParsingHash.Fnv1a("radius");
        internal static readonly uint F_shapeHeight    = VfxParsingHash.Fnv1a("height");
        internal static readonly uint F_shapeFlags     = VfxParsingHash.Fnv1a("flags");
        internal static readonly uint F_direction     = VfxParsingHash.Fnv1a("isDirectionOriented");
        internal static readonly uint F_texture       = VfxParsingHash.Fnv1a("texture");
        internal static readonly uint F_textureMult   = VfxParsingHash.Fnv1a("textureMult");
        internal static readonly uint F_emitterUvScroll = VfxParsingHash.Fnv1a("emitterUvScrollRate");
        internal static readonly uint F_texDiv        = VfxParsingHash.Fnv1a("texDiv");
        internal static readonly uint F_texDivMult    = VfxParsingHash.Fnv1a("texDivMult");
        internal static readonly uint F_numFrames     = VfxParsingHash.Fnv1a("numFrames");
        internal static readonly uint F_randomStart   = VfxParsingHash.Fnv1a("isRandomStartFrame");
        internal static readonly uint F_birthFrameRate= VfxParsingHash.Fnv1a("birthFrameRate");
        internal static readonly uint F_frameRate     = VfxParsingHash.Fnv1a("frameRate");
        internal static readonly uint F_birthUvScrollMult = VfxParsingHash.Fnv1a("birthUvScrollRateMult");
        internal static readonly uint F_birthUvOffsetMult = VfxParsingHash.Fnv1a("birthUVOffsetMult");
        internal static readonly uint F_particleUvScroll = VfxParsingHash.Fnv1a("particleUVScrollRate");
        internal static readonly uint F_particleUvRotate = VfxParsingHash.Fnv1a("particleUVRotateRate");
        internal static readonly uint F_birthUvRotate = VfxParsingHash.Fnv1a("birthUvRotateRate");
        internal static readonly uint F_particleUvScrollMult = VfxParsingHash.Fnv1a("ParticleIntegratedUvScrollMult");
        internal static readonly uint F_particleUvRotateMult = VfxParsingHash.Fnv1a("ParticleIntegratedUvRotateMult");
        internal static readonly uint F_birthUvRotateMult = VfxParsingHash.Fnv1a("birthUvRotateRateMult");
        internal static readonly uint F_uvScaleMult = VfxParsingHash.Fnv1a("uvScaleMult");
        internal static readonly uint F_uvRotationMult = VfxParsingHash.Fnv1a("UvRotationMult");
        internal static readonly uint F_texAddressMult = VfxParsingHash.Fnv1a("texAddressModeMult");
        internal static readonly uint F_textureMultFlipV = VfxParsingHash.Fnv1a("TextureMultFilpV");
        internal static readonly uint F_textureMultFlipU = VfxParsingHash.Fnv1a("TextureMultFilpU");
        internal static readonly uint F_textureMultTransformCenter = VfxParsingHash.Fnv1a("uvTransformCenterMult");
        internal static readonly uint F_textureMultClampUv = VfxParsingHash.Fnv1a("uvScrollClampMult");
        internal static readonly uint F_textureMultEmitterUvScroll = VfxParsingHash.Fnv1a("emitterUvScrollRateMult");
        internal static readonly uint F_birthUvOffset = VfxParsingHash.Fnv1a("birthUVOffset");
        internal static readonly uint F_uvScale       = VfxParsingHash.Fnv1a("uvScale");
        internal static readonly uint F_uvRotation    = VfxParsingHash.Fnv1a("uvRotation");
        internal static readonly uint F_uvTransformCenter = VfxParsingHash.Fnv1a("uvTransformCenter");
        internal static readonly uint F_primitive     = VfxParsingHash.Fnv1a("primitive");
        internal static readonly uint F_startFrame    = VfxParsingHash.Fnv1a("startFrame");
        internal static readonly uint F_legacySimple  = VfxParsingHash.Fnv1a("LegacySimple");
        internal static readonly uint F_legacyBirthScale = VfxParsingHash.Fnv1a("birthScale");
        internal static readonly uint F_legacyScale = VfxParsingHash.Fnv1a("scale");
        internal static readonly uint F_legacyBirthRotation = VfxParsingHash.Fnv1a("birthRotation");
        internal static readonly uint F_legacyBirthRotVel = VfxParsingHash.Fnv1a("birthRotationalVelocity");
        internal static readonly uint F_legacyScaleBias = VfxParsingHash.Fnv1a("scaleBias");
        internal static readonly uint F_legacyRotation = VfxParsingHash.Fnv1a("rotation");
        internal static readonly uint F_legacyLockedToEmitter = VfxParsingHash.Fnv1a("lockedToEmitter");
        internal static readonly uint F_legacyHasFixedOrbit = VfxParsingHash.Fnv1a("hasFixedOrbit");
        internal static readonly uint F_legacyFixedOrbitType = VfxParsingHash.Fnv1a("fixedOrbitType");
        internal static readonly uint F_legacyOrientation = VfxParsingHash.Fnv1a("orientation");
        internal static readonly uint F_legacyParticleBind = VfxParsingHash.Fnv1a("particleBind");
        internal static readonly uint F_legacyUvScrollRate = VfxParsingHash.Fnv1a("uvScrollRate");
        internal static readonly uint F_legacyScaleUpFromOrigin = VfxParsingHash.Fnv1a("scaleUpFromOrigin");
        internal static readonly uint F_shape = VfxParsingHash.Fnv1a("shape");
        internal static readonly uint F_distortionDefinition = VfxParsingHash.Fnv1a("distortionDefinition");
        internal static readonly uint F_distortion = VfxParsingHash.Fnv1a("distortion");
        internal static readonly uint F_distortionMode = VfxParsingHash.Fnv1a("distortionMode");
        internal static readonly uint F_normalMapTexture = VfxParsingHash.Fnv1a("normalMapTexture");
        internal static readonly uint F_alphaErosionDefinition = VfxParsingHash.Fnv1a("alphaErosionDefinition");
        internal static readonly uint F_erosionMapName = VfxParsingHash.Fnv1a("erosionMapName");
        internal static readonly uint F_erosionDriveCurve = VfxParsingHash.Fnv1a("erosionDriveCurve");
        internal static readonly uint F_useLingerErosionDrive = VfxParsingHash.Fnv1a("UseLingerErosionDriveCurve");
        internal static readonly uint F_lingerErosionDrive = VfxParsingHash.Fnv1a("LingerErosionDriveCurve");
        internal static readonly uint F_erosionDriveSource = VfxParsingHash.Fnv1a("erosionDriveSource");
        internal static readonly uint F_erosionFeatherIn = VfxParsingHash.Fnv1a("erosionFeatherIn");
        internal static readonly uint F_erosionFeatherOut = VfxParsingHash.Fnv1a("erosionFeatherOut");
        internal static readonly uint F_erosionSliceWidth = VfxParsingHash.Fnv1a("erosionSliceWidth");
        internal static readonly uint F_erosionMapAddressMode = VfxParsingHash.Fnv1a("erosionMapAddressMode");
        internal static readonly uint F_erosionMapChannelMixer = VfxParsingHash.Fnv1a("erosionMapChannelMixer");
        internal static readonly uint F_softParticleParams = VfxParsingHash.Fnv1a("softParticleParams");
        internal static readonly uint F_softBeginIn = VfxParsingHash.Fnv1a("beginIn");
        internal static readonly uint F_softDeltaIn = VfxParsingHash.Fnv1a("deltaIn");
        internal static readonly uint F_softBeginOut = VfxParsingHash.Fnv1a("beginOut");
        internal static readonly uint F_softDeltaOut = VfxParsingHash.Fnv1a("deltaOut");
        internal static readonly uint F_reflectionDefinition = VfxParsingHash.Fnv1a("reflectionDefinition");
        internal static readonly uint F_reflectionOpacityDirect = VfxParsingHash.Fnv1a("reflectionOpacityDirect");
        internal static readonly uint F_reflectionOpacityGlancing = VfxParsingHash.Fnv1a("reflectionOpacityGlancing");
        internal static readonly uint F_reflectionFresnel = VfxParsingHash.Fnv1a("reflectionFresnel");
        internal static readonly uint F_fresnel = VfxParsingHash.Fnv1a("fresnel");
        internal static readonly uint F_fresnelColor = VfxParsingHash.Fnv1a("fresnelColor");
        internal static readonly uint F_reflectionFresnelColor = VfxParsingHash.Fnv1a("reflectionFresnelColor");
        internal static readonly uint F_reflectionMapTexture = VfxParsingHash.Fnv1a("reflectionMapTexture");
        internal static readonly uint F_childParticleSet = VfxParsingHash.Fnv1a("childParticleSetDefinition");
        internal static readonly uint F_childrenIdentifiers = VfxParsingHash.Fnv1a("childrenIdentifiers");
        internal static readonly uint F_boneToSpawnAt = VfxParsingHash.Fnv1a("boneToSpawnAt");
        internal static readonly uint F_childEmitOnDeath = VfxParsingHash.Fnv1a("childEmitOnDeath");
        internal static readonly uint F_childrenProbability = VfxParsingHash.Fnv1a("childrenProbability");
        internal static readonly uint F_parentInheritance = VfxParsingHash.Fnv1a("ParentInheritanceDefinition");
        internal static readonly uint F_relativeOffset = VfxParsingHash.Fnv1a("RelativeOffset");
        internal static readonly uint F_inheritanceMode = VfxParsingHash.Fnv1a("Mode");
        internal static readonly uint F_effectName = VfxParsingHash.Fnv1a("effectName");
        internal static readonly uint F_effect = VfxParsingHash.Fnv1a("effect");
        internal static readonly uint F_effectKey = VfxParsingHash.Fnv1a("effectKey");
        internal static readonly uint F_fieldCollection = VfxParsingHash.Fnv1a("fieldCollectionDefinition");
        internal static readonly uint F_fieldAccelerationDefinitions = VfxParsingHash.Fnv1a("fieldAccelerationDefinitions");
        internal static readonly uint F_fieldAttractionDefinitions = VfxParsingHash.Fnv1a("fieldAttractionDefinitions");
        internal static readonly uint F_fieldDragDefinitions = VfxParsingHash.Fnv1a("fieldDragDefinitions");
        internal static readonly uint F_fieldOrbitalDefinitions = VfxParsingHash.Fnv1a("fieldOrbitalDefinitions");
        internal static readonly uint F_fieldNoiseDefinitions = VfxParsingHash.Fnv1a("fieldNoiseDefinitions");
        internal static readonly uint F_isLocalSpace = VfxParsingHash.Fnv1a("isLocalSpace");
        internal static readonly uint F_position = VfxParsingHash.Fnv1a("position");
        internal static readonly uint F_radius = VfxParsingHash.Fnv1a("radius");
        internal static readonly uint F_strength = VfxParsingHash.Fnv1a("strength");
        internal static readonly uint F_directionField = VfxParsingHash.Fnv1a("direction");
        internal static readonly uint F_frequency = VfxParsingHash.Fnv1a("frequency");
        internal static readonly uint F_velocityDelta = VfxParsingHash.Fnv1a("velocityDelta");
        internal static readonly uint F_axisFraction = VfxParsingHash.Fnv1a("axisFraction");


        internal static readonly uint F_meshDef       = 0x0d89732d; // VfxPrimitiveMesh's VfxMeshDefinitionData field
        internal static readonly uint F_simpleMesh    = VfxParsingHash.Fnv1a("mSimpleMeshName");
        internal static readonly uint F_meshName      = VfxParsingHash.Fnv1a("mMeshName");
        internal static readonly uint F_meshAlignPitch = VfxParsingHash.Fnv1a("AlignPitchToCamera");
        internal static readonly uint F_meshAlignYaw = VfxParsingHash.Fnv1a("AlignYawToCamera");
        internal static readonly uint F_submeshesToDrawAlways = VfxParsingHash.Fnv1a("mSubmeshesToDrawAlways");
        internal static readonly uint F_submeshesToDraw = VfxParsingHash.Fnv1a("mSubmeshesToDraw");
        internal static readonly uint F_birthUvScroll = VfxParsingHash.Fnv1a("birthUvScrollRate");
        internal static readonly uint F_meshSkeleton  = 0x90595a15; // VfxMeshDefinitionData skeleton field
        internal static readonly uint F_meshAnim      = VfxParsingHash.Fnv1a("mAnimationName");
        internal static readonly uint F_meshAnimationVariants = VfxParsingHash.Fnv1a("mAnimationVariants");
        internal static readonly uint F_trailDefinition = VfxParsingHash.Fnv1a("mTrail");
        internal static readonly uint F_beamDefinition = VfxParsingHash.Fnv1a("mBeam");
        internal static readonly uint F_trailBirthTilingSize = VfxParsingHash.Fnv1a("mBirthTilingSize");
        internal static readonly uint F_trailSmoothingMode = VfxParsingHash.Fnv1a("mSmoothingMode");
        internal static readonly uint F_trailMode = VfxParsingHash.Fnv1a("mMode");
        internal static readonly uint F_trailMaxAddedPerFrame = VfxParsingHash.Fnv1a("mMaxAddedPerFrame");
        internal static readonly uint F_trailCutoff = VfxParsingHash.Fnv1a("mCutoff");
        internal static readonly uint F_beamTrailMode = VfxParsingHash.Fnv1a("mTrailMode");
        internal static readonly uint F_beamSegments = VfxParsingHash.Fnv1a("mSegments");
        internal static readonly uint F_beamColor = VfxParsingHash.Fnv1a("mAnimatedColorWithDistance");
        internal static readonly uint F_beamColorBound = VfxParsingHash.Fnv1a("mIsColorBindedWithDistance");
        internal static readonly uint F_beamSourceOffset = VfxParsingHash.Fnv1a("mLocalSpaceSourceOffset");
        internal static readonly uint F_beamTargetOffset = VfxParsingHash.Fnv1a("mLocalSpaceTargetOffset");

        // primitive class hashes we treat as "mesh"
        internal static readonly uint PrimMesh = VfxParsingHash.Fnv1a("VfxPrimitiveMesh");
        internal static readonly uint PrimAttachedMesh = VfxParsingHash.Fnv1a("VfxPrimitiveAttachedMesh");
        internal static readonly uint PrimArbitraryQuad = VfxParsingHash.Fnv1a("VfxPrimitiveArbitraryQuad");
        internal static readonly uint PrimCameraQuad = VfxParsingHash.Fnv1a("VfxPrimitiveCameraQuad");
        internal static readonly uint PrimCameraUnitQuad = VfxParsingHash.Fnv1a("VfxPrimitiveCameraUnitQuad");
        internal static readonly uint PrimCameraTrail = VfxParsingHash.Fnv1a("VfxPrimitiveCameraTrail");
        internal static readonly uint PrimArbitraryTrail = VfxParsingHash.Fnv1a("VfxPrimitiveArbitraryTrail");
        internal static readonly uint PrimRay = VfxParsingHash.Fnv1a("VfxPrimitiveRay");
        internal static readonly uint PrimBeam = VfxParsingHash.Fnv1a("VfxPrimitiveBeam");
        internal static readonly uint PrimCameraSegmentBeam = VfxParsingHash.Fnv1a("VfxPrimitiveCameraSegmentBeam");
        internal static readonly uint PrimPlanarProjection = VfxParsingHash.Fnv1a("VfxPrimitivePlanarProjection");
        internal static readonly uint ShapeLegacy = VfxParsingHash.Fnv1a("VfxShapeLegacy");
        internal static readonly uint ShapeOld = VfxParsingHash.Fnv1a("VfxShape");
        internal static readonly uint ShapePoint = VfxParsingHash.Fnv1a("VfxShapePointDoNotUse");
        internal static readonly uint ShapeBox = VfxParsingHash.Fnv1a("VfxShapeBox");
        internal static readonly uint ShapeSphere = VfxParsingHash.Fnv1a("VfxShapeSphere");
        internal static readonly uint ShapeCylinder = VfxParsingHash.Fnv1a("VfxShapeCylinder");
    }
}
